### ISSUE TITLE
TypeError: 'NoneType'

### ISSUE THREAD

**Issue by vrtisworks** [bmillham/DJDB#2]
I am running Python 2.7.9 on Lubuntu

When I scan my library.. DJDB dies with the following in the log (I tried a few fixes, but my python skills aren't good enough).

`
Running full scan
Estimate Started
Ignoring file time to run full scan
Field already in database
Getting catalogs
Scan Completed
Ignoring file time to run full scan
Field already in database
Getting catalogs
/home/nick/DJDB/LibScan/**init**.py:282: Warning: Out of range value for column 'bitrate' at row 1
  info.tracknumber, info.modification_time, time(), row['sid']))
Files were updated in the catalog
Traceback (most recent call last):
  File "/home/nick/DJDB/LibScan/**init**.py", line 141, in scan_files
    info = SimpleTag(f+x, self.options['program'])
  File "/home/nick/DJDB/SimpleTag/**init**.py", line 40, in **init**
    self._fetch_tags()
  File "/home/nick/DJDB/SimpleTag/__init__.py", line 48, in _fetch_tags
    self._album = Name(self._string_tag('album'), self.options['prefixes'])
  File "/home/nick/DJDB/SimpleTag/__init__.py", line 89, in _string_tag
    self.warnings(field, "Empty required string tag")
TypeError: 'NoneType' object is not callable
nick@mylinux:~/DJDB$ 

`

**Comment by bmillham** [comment]
It appears that there is a file with bad bitrate info in it. I created a temporary fix to ignore the bad bitrate. It will print to the console the offending files song title, and the offending bitrate. Please try out the fix, and post the resulting messages from the console so I can create a more permanent fix.

**Comment by vrtisworks** [comment]
Well, I tried the new code, and I have posted the log below.  But the bad bitrate really isn't the problem.  The code continues after the warning.  It is the TypeError in SimpleTag that causes the program to quit scanning (the GUI window stays open, but the progress bar doesn't move).

Thanks for looking into this.

`
nick@mylinux:~/DJDB$ python djdb.py

*\* (djdb.py:3420): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Running full scan
Estimate Started
Ignoring file time to run full scan
Field already in database
Getting catalogs
Scan Completed
Ignoring file time to run full scan
Field already in database
Getting catalogs
/home/nick/DJDB/LibScan/**init**.py:283: Warning: Out of range value for column 'bitrate' at row 1
  info.tracknumber, info.modification_time, time(), row['sid']))
Files were updated in the catalog
Scan Completed
Checking for removed songs
nick@mylinux:~/DJDB$ 

`

**Comment by vrtisworks** [comment]
Well, I hacked a fix(?).    I have attached the two files I changed.  I don't know python good enough to know exactly which changes fixed things.

[fix_track_disc.py.txt](https://github.com/bmillham/DJDB/files/249079/fix_track_disc.py.txt)
[**init**.py.txt](https://github.com/bmillham/DJDB/files/249078/__init__.py.txt)

**Comment by bmillham** [comment]
I dug deeper into this, and now I'm confused. The init.py that you supplied above is from SimpleTag/__init__.py, but it does not match what's in the git repository. Try checking out the repository in a new directory, and run djdb.py again and see if it works properly.

**Comment by bmillham** [comment]
I just commited a change that should fix the problem. You were on the right track with your hack, but there was a much simpler fix.

**Comment by vrtisworks** [comment]
That works.. Thank you.. :)
